from cartolas.config import PARQUET_FOLDER_YEAR, SCHEMA
from cartolas.read import read_parquet_cartolas_lazy
from cartolas.save import save_lazyframe_to_parquet
from cartolas.transform import transform_cartola_folder
from cartolas.update import update_parquet
from cartolas.update_by_year import update_parquet_by_year
